# Delete a person
DELETE http://localhost:3001/api/persons/1

###
# Add a person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Axelle Lu",
  "number": "6667777666"
}
###
PUT http://localhost:3001/api/persons/4
Content-Type: application/json

{
  "name": "",
  "number": "1234567890"
}
###
# Get all persons
GET http://localhost:3001/api/persons
###
# Get a person by id
GET http://localhost:3001/api/persons/1
